export const FETCH_ALL_POKEMON = "FETCH_ALL_POKEMON";
export const FETCH_POKEMON = "FETCH_POKEMON";
export const FETCH_POKEMON_SUCCESS = "FETCH_POKEMON_SUCCESS";
export const FETCH_POKEMON_FAILED = "FETCH_POKEMON_FAILED";
